baseURL = 'https://www.selenedeployment.com/'
languageCode = 'en-us'
title = 'Romain´s Portfolio'
theme = "basic"
author = "Romain"
description = "My portfolio site"
googleAnalytics = "UA-xxxxxxxxxxxx"